-- Ejercicio 1)
use bonus_track;

-- 1)
SET SQL_SAFE_UPDATES = 0;
UPDATE TOP_SPOTIFY SET TITULO = UPPER(TITULO), ARTISTA = UPPER(ARTISTA);
-- 2)
ALTER TABLE TOP_SPOTIFY ADD PERMANENCIA INT;
UPDATE TOP_SPOTIFY SET PERMANENCIA = YEAR(CURDATE()) - ANO;
-- 3)
CREATE TABLE ULTIMOS_LANZAMIENTOS SELECT * FROM TOP_SPOTIFY WHERE PERMANENCIA <= 3;
DELETE FROM TOP_SPOTIFY WHERE PERMANENCIA <=3;
-- 4)
INSERT INTO TOP_SPOTIFY VALUES
	(610, 'GOD CONTROL', 'MADONNA', 'POP', 2018, 3);
-- 5)
INSERT INTO ULTIMOS_LANZAMIENTOS (ID, TITULO, ARTISTA, GENERO, ANO, PERMANENCIA) SELECT ID, TITULO, ARTISTA, GENERO, ANO, PERMANENCIA FROM TOP_SPOTIFY WHERE PERMANENCIA <= 3;
DELETE FROM TOP_SPOTIFY WHERE PERMANENCIA <= 3;

-- Ejercicio 2)
use libreria;

-- 1)
SET SQL_SAFE_UPDATES = 0;
UPDATE AUTORES SET NOMBRE = 'Esteban' WHERE APELLIDO = 'ECHEVERRÍA';
-- 2)
ALTER TABLE EMPLEADOS ADD PERMANENCIA INT;
UPDATE EMPLEADOS SET PERMANENCIA = TIMESTAMPDIFF(YEAR, FECHA_INGRESO, CURDATE());
-- 3)
ALTER TABLE LIBROS ADD PRECIO_PUBLICO FLOAT;
UPDATE LIBROS SET PRECIO_PUBLICO = ROUND(PRECIO * 1.21, 2);

-- Ejercicio 3)

-- 1)
CREATE TABLE EMPLEADOS_ANTERIORES SELECT * FROM EMPLEADOS WHERE APELLIDO IN ('THOMAS', 'PEREIRA', 'DEVO');
DELETE FROM EMPLEADOS WHERE APELLIDO IN ('THOMAS', 'PEREIRA', 'DEVO');
-- 2)
INSERT INTO EMPLEADOS_ANTERIORES SELECT * FROM EMPLEADOS WHERE APELLIDO = 'CRUZ';
DELETE FROM EMPLEADOS WHERE APELLIDO = 'CRUZ';


select * from autores;
SELECT * FROM ULTIMOS_LANZAMIENTOS;